produit_index:
    path: /produit
    methods: GET
    controller: App\Controller\ProduitController::index

app_produit_new:
    path: /produit/new
    methods: [GET, POST]
    controller: App\Controller\ProduitController::new

app_produit_show:
    path: /produit/{id_produit}
    controller: App\Controller\ProduitController::show
    methods: GET

app_produit_edit:
    path: /{id_produit}/edit
    methods: [GET, POST]
    controller: App\Controller\ProduitController::edit

app_produit_delete:
    path: /{id_produit}
    methods: POST
    controller: App\Controller\ProduitController::delete
